import mongoose from "mongoose";

const ROLE = {
  Owner: "owner",
  ADMIN: "admin",
  MANAGER: "manager",
  SUPERVISOR: "supervisor",
  MODERATOR: "moderator",
  USER: "user",
};

const adminSchema = new mongoose.Schema(
  {
    fullname: { type: String, required: true },
    email: { type: String, required: true, unique: true },
    phone: { type: String },
    profileImage: {
      type: String,
      default: "/all-images/profile/profile.jpeg",
    },
    password: { type: String, required: true },

    role: {
      type: String,
      enum: Object.values(ROLE),
      default: ROLE.USER,
      required: true,
    },
    addedBy: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Admin",
      required: false,
    },

    permissions: {
      canCreateHotel: { type: Boolean, default: false },
      canReadHotel: { type: Boolean, default: false },
      canUpdateHotel: { type: Boolean, default: false },
      canDeleteHotel: { type: Boolean, default: false },
      canCreateAccommodation: { type: Boolean, default: false },
      canReadAccommodation: { type: Boolean, default: false },
      canUpdateAccommodation: { type: Boolean, default: false },
      canDeleteAccommodation: { type: Boolean, default: false },
      canCreatePageExp: { type: Boolean, default: false },
      canReadPageExp: { type: Boolean, default: false },
      canUpdatePageExp: { type: Boolean, default: false },
      canDeletePageExp: { type: Boolean, default: false },
      canCreateGallery: { type: Boolean, default: false },
      canReadGallery: { type: Boolean, default: false },
      canUpdateGallery: { type: Boolean, default: false },
      canDeleteGallery: { type: Boolean, default: false },
      canCreateService: { type: Boolean, default: false },
      canReadService: { type: Boolean, default: false },
      canUpdateService: { type: Boolean, default: false },
      canDeleteService: { type: Boolean, default: false },
      canCreateOffer: { type: Boolean, default: false },
      canReadOffer: { type: Boolean, default: false },
      canUpdateOffer: { type: Boolean, default: false },
      canDeleteOffer: { type: Boolean, default: false },
      canCreateExperience: { type: Boolean, default: false },
      canReadExperience: { type: Boolean, default: false },
      canUpdateExperience: { type: Boolean, default: false },
      canDeleteExperience: { type: Boolean, default: false },
      canCreateBlog: { type: Boolean, default: false },
      canReadBlog: { type: Boolean, default: false },
      canUpdateBlog: { type: Boolean, default: false },
      canDeleteBlog: { type: Boolean, default: false },
      canCreateBlogContent: { type: Boolean, default: false },
      canReadBlogContent: { type: Boolean, default: false },
      canUpdateBlogContent: { type: Boolean, default: false },
      canDeleteBlogContent: { type: Boolean, default: false },
      canCreateHomeSlider: { type: Boolean, default: false },
      canReadHomeSlider: { type: Boolean, default: false },
      canUpdateHomeSlider: { type: Boolean, default: false },
      canDeleteHomeSlider: { type: Boolean, default: false },
      canCreateHomeTop: { type: Boolean, default: false },
      canReadHomeTop: { type: Boolean, default: false },
      canUpdateHomeTop: { type: Boolean, default: false },
      canDeleteHomeTop: { type: Boolean, default: false },
      canCreateHomeMiddle: { type: Boolean, default: false },
      canReadHomeMiddle: { type: Boolean, default: false },
      canUpdateHomeMiddle: { type: Boolean, default: false },
      canDeleteHomeMiddle: { type: Boolean, default: false },
      canCreateHomeExp: { type: Boolean, default: false },
      canReadHomeExp: { type: Boolean, default: false },
      canUpdateHomeExp: { type: Boolean, default: false },
      canDeleteHomeExp: { type: Boolean, default: false },
      canCreateHomeBottom: { type: Boolean, default: false },
      canReadHomeBottom: { type: Boolean, default: false },
      canUpdateHomeBottom: { type: Boolean, default: false },
      canDeleteHomeBottom: { type: Boolean, default: false },
      canCreateAboutTop: { type: Boolean, default: false },
      canReadAboutTop: { type: Boolean, default: false },
      canUpdateAboutTop: { type: Boolean, default: false },
      canDeleteAboutTop: { type: Boolean, default: false },
      canCreateAboutMiddle: { type: Boolean, default: false },
      canReadAboutMiddle: { type: Boolean, default: false },
      canUpdateAboutMiddle: { type: Boolean, default: false },
      canDeleteAboutMiddle: { type: Boolean, default: false },
      canCreateAboutBottom: { type: Boolean, default: false },
      canReadAboutBottom: { type: Boolean, default: false },
      canUpdateAboutBottom: { type: Boolean, default: false },
      canDeleteAboutBottom: { type: Boolean, default: false },
      canCreateContactContent: { type: Boolean, default: false },
      canReadContactContent: { type: Boolean, default: false },
      canUpdateContactContent: { type: Boolean, default: false },
      canDeleteContactContent: { type: Boolean, default: false },
      canCreateUsers: { type: Boolean, default: false },
      canReadUsers: { type: Boolean, default: false },
      canUpdateUsers: { type: Boolean, default: false },
      canDeleteUsers: { type: Boolean, default: false },
      canViewReports: { type: Boolean, default: false },
      canPrintReports: { type: Boolean, default: false },
      canViewPermissions: { type: Boolean, default: false },
    },

    resetPasswordToken: String,
    resetPasswordExpire: Date,
  },
  { timestamps: true }
);
adminSchema.pre("save", function (next) {
  if (this.isNew) {
    switch (this.role) {
      case "owner":
        this.permissions = {
          canCreateHotel: true,
          canReadHotel: true,
          canUpdateHotel: true,
          canDeleteHotel: true,
          canCreateAccommodation: true,
          canReadAccommodation: true,
          canUpdateAccommodation: true,
          canDeleteAccommodation: true,
          canCreatePageExp: true,
          canReadPageExp: true,
          canUpdatePageExp: true,
          canDeletePageExp: true,
          canCreateGallery: true,
          canReadGallery: true,
          canUpdateGallery: true,
          canDeleteGallery: true,
          canCreateService: true,
          canReadService: true,
          canUpdateService: true,
          canDeleteService: true,
          canCreateExperience: true,
          canReadExperience: true,
          canUpdateExperience: true,
          canDeleteExperience: true,
          canCreateBlog: true,
          canReadBlog: true,
          canUpdateBlog: true,
          canDeleteBlog: true,
          canCreateBlogContent: true,
          canReadBlogContent: true,
          canUpdateBlogContent: true,
          canDeleteBlogContent: true,
          canCreateHomeSlider: true,
          canReadHomeSlider: true,
          canUpdateHomeSlider: true,
          canDeleteHomeSlider: true,
          canCreateHomeTop: true,
          canReadHomeTop: true,
          canUpdateHomeTop: true,
          canDeleteHomeTop: true,
          canCreateHomeMiddle: true,
          canReadHomeMiddle: true,
          canUpdateHomeMiddle: true,
          canDeleteHomeMiddle: true,
          canCreateHomeExp: true,
          canReadHomeExp: true,
          canUpdateHomeExp: true,
          canDeleteHomeExp: true,
          canCreateHomeBottom: true,
          canReadHomeBottom: true,
          canUpdateHomeBottom: true,
          canDeleteHomeBottom: true,
          canCreateAboutTop: true,
          canReadAboutTop: true,
          canUpdateAboutTop: true,
          canDeleteAboutTop: true,
          canCreateAboutMiddle: true,
          canReadAboutMiddle: true,
          canUpdateAboutMiddle: true,
          canDeleteAboutMiddle: true,
          canCreateAboutBottom: true,
          canReadAboutBottom: true,
          canUpdateAboutBottom: true,
          canDeleteAboutBottom: true,
          canCreateContactContent: true,
          canReadContactContent: true,
          canUpdateContactContent: true,
          canDeleteContactContent: true,
          canCreateUsers: true,
          canReadUsers: true,
          canUpdateUsers: true,
          canDeleteUsers: true,
          canViewReports: true,
          canPrintReports: true,
          canViewPermissions: true,
        };
        break;
      case "admin":
        this.permissions = {
          canCreateHotel: true,
          canReadHotel: true,
          canUpdateHotel: true,
          canDeleteHotel: false,
          canCreateAccommodation: true,
          canReadAccommodation: true,
          canUpdateAccommodation: true,
          canDeleteAccommodation: false,
          canCreatePageExp: true,
          canReadPageExp: true,
          canUpdatePageExp: true,
          canDeletePageExp: false,
          canCreateGallery: true,
          canReadGallery: true,
          canUpdateGallery: true,
          canDeleteGallery: false,
          canCreateService: true,
          canReadService: true,
          canUpdateService: true,
          canDeleteService: false,
          canCreateOffer: true,
          canReadOffer: true,
          canUpdateOffer: true,
          canDeleteOffer: false,
          canCreateExperience: true,
          canReadExperience: true,
          canUpdateExperience: true,
          canDeleteExperience: false,
          canCreateBlog: true,
          canReadBlog: true,
          canUpdateBlog: true,
          canDeleteBlog: false,
          canCreateBlogContent: true,
          canReadBlogContent: true,
          canUpdateBlogContent: true,
          canDeleteBlogContent: false,
          canCreateHomeSlider: true,
          canReadHomeSlider: true,
          canUpdateHomeSlider: true,
          canDeleteHomeSlider: false,
          canCreateHomeTop: true,
          canReadHomeTop: true,
          canUpdateHomeTop: true,
          canDeleteHomeTop: false,
          canCreateHomeMiddle: true,
          canReadHomeMiddle: true,
          canUpdateHomeMiddle: true,
          canDeleteHomeMiddle: false,
          canCreateHomeExp: true,
          canReadHomeExp: true,
          canUpdateHomeExp: true,
          canDeleteHomeExp: false,
          canCreateHomeBottom: true,
          canReadHomeBottom: true,
          canUpdateHomeBottom: true,
          canDeleteHomeBottom: false,
          canCreateAboutTop: true,
          canReadAboutTop: true,
          canUpdateAboutTop: true,
          canDeleteAboutTop: false,
          canCreateAboutMiddle: true,
          canReadAboutMiddle: true,
          canUpdateAboutMiddle: true,
          canDeleteAboutMiddle: false,
          canCreateAboutBottom: true,
          canReadAboutBottom: true,
          canUpdateAboutBottom: true,
          canDeleteAboutBottom: false,
          canCreateContactContent: true,
          canReadContactContent: true,
          canUpdateContactContent: true,
          canDeleteContactContent: false,
          canCreateUsers: true,
          canReadUsers: true,
          canUpdateUsers: true,
          canDeleteUsers: false,
          canViewReports: true,
          canPrintReports: true,
          canViewPermissions: true,
        };
        break;
      case "manager":
        this.permissions = {
          canCreateHotel: false,
          canReadHotel: true,
          canUpdateHotel: false,
          canDeleteHotel: false,
          canCreateAccommodation: false,
          canReadAccommodation: true,
          canUpdateAccommodation: false,
          canDeleteAccommodation: false,
          canCreatePageExp: false,
          canReadPageExp: true,
          canUpdatePageExp: false,
          canDeletePageExp: false,
          canCreateGallery: false,
          canReadGallery: true,
          canUpdateGallery: false,
          canDeleteGallery: false,
          canCreateService: false,
          canReadService: true,
          canUpdateService: false,
          canDeleteService: false,
          canCreateOffer: false,
          canReadOffer: true,
          canUpdateOffer: false,
          canDeleteOffer: false,
          canCreateExperience: false,
          canReadExperience: true,
          canUpdateExperience: false,
          canDeleteExperience: false,
          canCreateBlog: false,
          canReadBlog: true,
          canUpdateBlog: false,
          canDeleteBlog: false,
          canCreateBlogContent: false,
          canReadBlogContent: true,
          canUpdateBlogContent: false,
          canDeleteBlogContent: false,
          canCreateHomeSlider: false,
          canReadHomeSlider: true,
          canUpdateHomeSlider: false,
          canDeleteHomeSlider: false,
          canCreateHomeTop: false,
          canReadHomeTop: true,
          canUpdateHomeTop: false,
          canDeleteHomeTop: false,
          canCreateHomeMiddle: false,
          canReadHomeMiddle: true,
          canUpdateHomeMiddle: false,
          canDeleteHomeMiddle: false,
          canCreateHomeExp: false,
          canReadHomeExp: true,
          canUpdateHomeExp: false,
          canDeleteHomeExp: false,
          canCreateHomeBottom: false,
          canReadHomeBottom: true,
          canUpdateHomeBottom: false,
          canDeleteHomeBottom: false,
          canCreateAboutTop: false,
          canReadAboutTop: true,
          canUpdateAboutTop: false,
          canDeleteAboutTop: false,
          canCreateAboutMiddle: false,
          canReadAboutMiddle: true,
          canUpdateAboutMiddle: false,
          canDeleteAboutMiddle: false,
          canCreateAboutBottom: false,
          canReadAboutBottom: true,
          canUpdateAboutBottom: false,
          canDeleteAboutBottom: false,
          canCreateContactContent: false,
          canReadContactContent: true,
          canUpdateContactContent: false,
          canDeleteContactContent: false,
          canCreateUsers: false,
          canReadUsers: true,
          canUpdateUsers: false,
          canDeleteUsers: false,
          canViewReports: true,
          canPrintReports: true,
          canViewPermissions: false,
        };
        break;
      case "supervisor":
        this.permissions = {
          canCreateHotel: false,
          canReadHotel: true,
          canUpdateHotel: false,
          canDeleteHotel: false,
          canCreateAccommodation: false,
          canReadAccommodation: true,
          canUpdateAccommodation: false,
          canDeleteAccommodation: false,
          canCreatePageExp: false,
          canReadPageExp: true,
          canUpdatePageExp: false,
          canDeletePageExp: false,
          canCreateGallery: false,
          canReadGallery: true,
          canUpdateGallery: false,
          canDeleteGallery: false,
          canCreateService: false,
          canReadService: true,
          canUpdateService: false,
          canDeleteService: false,
          canCreateOffer: false,
          canReadOffer: true,
          canUpdateOffer: false,
          canDeleteOffer: false,
          canCreateExperience: false,
          canReadExperience: true,
          canUpdateExperience: false,
          canDeleteExperience: false,
          canCreateBlog: false,
          canReadBlog: true,
          canUpdateBlog: false,
          canDeleteBlog: false,
          canCreateBlogContent: false,
          canReadBlogContent: true,
          canUpdateBlogContent: false,
          canDeleteBlogContent: false,
          canCreateHomeSlider: false,
          canReadHomeSlider: true,
          canUpdateHomeSlider: false,
          canDeleteHomeSlider: false,
          canCreateHomeTop: false,
          canReadHomeTop: true,
          canUpdateHomeTop: false,
          canDeleteHomeTop: false,
          canCreateHomeMiddle: false,
          canReadHomeMiddle: true,
          canUpdateHomeMiddle: false,
          canDeleteHomeMiddle: false,
          canCreateHomeExp: false,
          canReadHomeExp: true,
          canUpdateHomeExp: false,
          canDeleteHomeExp: false,
          canCreateHomeBottom: false,
          canReadHomeBottom: true,
          canUpdateHomeBottom: false,
          canDeleteHomeBottom: false,
          canCreateAboutTop: false,
          canReadAboutTop: true,
          canUpdateAboutTop: false,
          canDeleteAboutTop: false,
          canCreateAboutMiddle: false,
          canReadAboutMiddle: true,
          canUpdateAboutMiddle: false,
          canDeleteAboutMiddle: false,
          canCreateAboutBottom: false,
          canReadAboutBottom: true,
          canUpdateAboutBottom: false,
          canDeleteAboutBottom: false,
          canCreateContactContent: false,
          canReadContactContent: true,
          canUpdateContactContent: false,
          canDeleteContactContent: false,
          canCreateUsers: false,
          canReadUsers: true,
          canUpdateUsers: false,
          canDeleteUsers: false,
          canViewReports: true,
          canPrintReports: true,
          canViewPermissions: false,
        };
        break;
      case "moderator":
        this.permissions = {
          canCreateHotel: false,
          canReadHotel: true,
          canUpdateHotel: true,
          canDeleteHotel: false,
          canCreateAccommodation: false,
          canReadAccommodation: true,
          canUpdateAccommodation: true,
          canDeleteAccommodation: false,
          canCreatePageExp: false,
          canReadPageExp: true,
          canUpdatePageExp: true,
          canDeletePageExp: false,
          canCreateGallery: false,
          canReadGallery: true,
          canUpdateGallery: true,
          canDeleteGallery: false,
          canCreateService: false,
          canReadService: true,
          canUpdateService: true,
          canDeleteService: false,
          canCreateOffer: false,
          canReadOffer: true,
          canUpdateOffer: true,
          canDeleteOffer: false,
          canCreateExperience: false,
          canReadExperience: true,
          canUpdateExperience: true,
          canDeleteExperience: false,
          canCreateBlog: false,
          canReadBlog: true,
          canUpdateBlog: true,
          canDeleteBlog: false,
          canCreateBlogContent: false,
          canReadBlogContent: true,
          canUpdateBlogContent: true,
          canDeleteBlogContent: false,
          canCreateHomeSlider: false,
          canReadHomeSlider: true,
          canUpdateHomeSlider: true,
          canDeleteHomeSlider: false,
          canCreateHomeTop: false,
          canReadHomeTop: true,
          canUpdateHomeTop: true,
          canDeleteHomeTop: false,
          canCreateHomeMiddle: false,
          canReadHomeMiddle: true,
          canUpdateHomeMiddle: true,
          canDeleteHomeMiddle: false,
          canCreateHomeExp: false,
          canReadHomeExp: true,
          canUpdateHomeExp: true,
          canDeleteHomeExp: false,
          canCreateHomeBottom: false,
          canReadHomeBottom: true,
          canUpdateHomeBottom: true,
          canDeleteHomeBottom: false,
          canCreateAboutTop: false,
          canReadAboutTop: true,
          canUpdateAboutTop: true,
          canDeleteAboutTop: false,
          canCreateAboutMiddle: false,
          canReadAboutMiddle: true,
          canUpdateAboutMiddle: true,
          canDeleteAboutMiddle: false,
          canCreateAboutBottom: false,
          canReadAboutBottom: true,
          canUpdateAboutBottom: true,
          canDeleteAboutBottom: false,
          canCreateContactContent: false,
          canReadContactContent: true,
          canUpdateContactContent: true,
          canDeleteContactContent: false,
          canCreateUsers: true,
          canReadUsers: true,
          canUpdateUsers: true,
          canDeleteUsers: true,
          canViewReports: true,
          canPrintReports: false,
          canViewPermissions: false,
        };
        break;
      default:
        this.permissions = {
          canCreateHotel: false,
          canReadHotel: false,
          canUpdateHotel: false,
          canDeleteHotel: false,
          canCreateAccommodation: false,
          canReadAccommodation: false,
          canUpdateAccommodation: false,
          canDeleteAccommodation: false,
          canCreatePageExp: false,
          canReadPageExp: false,
          canUpdatePageExp: false,
          canDeletePageExp: false,
          canCreateGallery: false,
          canReadGallery: false,
          canUpdateGallery: false,
          canDeleteGallery: false,
          canCreateService: false,
          canReadService: false,
          canUpdateService: false,
          canDeleteService: false,
          canCreateOffer: false,
          canReadOffer: false,
          canUpdateOffer: false,
          canDeleteOffer: false,
          canCreateExperience: false,
          canReadExperience: false,
          canUpdateExperience: false,
          canDeleteExperience: false,
          canCreateBlog: false,
          canReadBlog: false,
          canUpdateBlog: false,
          canDeleteBlog: false,
          canCreateBlogContent: false,
          canReadBlogContent: false,
          canUpdateBlogContent: false,
          canDeleteBlogContent: false,
          canCreateHomeSlider: false,
          canReadHomeSlider: false,
          canUpdateHomeSlider: false,
          canDeleteHomeSlider: false,
          canCreateHomeTop: false,
          canReadHomeTop: false,
          canUpdateHomeTop: false,
          canDeleteHomeTop: false,
          canCreateHomeMiddle: false,
          canReadHomeMiddle: false,
          canUpdateHomeMiddle: false,
          canDeleteHomeMiddle: false,
          canCreateHomeExp: false,
          canReadHomeExp: false,
          canUpdateHomeExp: false,
          canDeleteHomeExp: false,
          canCreateHomeBottom: false,
          canReadHomeBottom: false,
          canUpdateHomeBottom: false,
          canDeleteHomeBottom: false,
          canCreateAboutTop: false,
          canReadAboutTop: false,
          canUpdateAboutTop: false,
          canDeleteAboutTop: false,
          canCreateAboutMiddle: false,
          canReadAboutMiddle: false,
          canUpdateAboutMiddle: false,
          canDeleteAboutMiddle: false,
          canCreateAboutBottom: false,
          canReadAboutBottom: false,
          canUpdateAboutBottom: false,
          canDeleteAboutBottom: false,
          canCreateContactContent: false,
          canReadContactContent: false,
          canUpdateContactContent: false,
          canDeleteContactContent: false,
          canCreateUsers: false,
          canReadUsers: false,
          canUpdateUsers: false,
          canDeleteUsers: false,
          canViewReports: false,
          canPrintReports: false,
          canViewPermissions: false,
        };
        break;
    }
  }
  next();
});

export default mongoose.models.Admin || mongoose.model("Admin", adminSchema);
